In [1]:
import numpy as np


In [4]:
# 1nd
myarray1 = np.array([10,20,30])
myarray2 = np.array([5,2,4])

print(myarray1 + myarray2)
print(myarray1 - myarray2)
print(myarray1 * myarray2)
print(myarray1 / myarray2)

[15 22 34]
[ 5 18 26]
[ 50  40 120]
[ 2.  10.   7.5]


In [6]:
# 2nd
myarray3 = np.array([ [1,4],[5,9] ])
myarray4 = np.array([ [2,7],[10,5] ])

print(myarray3 + myarray4)


[[ 3 11]
 [15 14]]


In [9]:
# 1nd
myarray5 = np.array([10,20,30])
print(myarray5.min())
print(myarray5.max())
print(myarray5.sum())

10
30
60


In [11]:
# 2nd
myarray6 = np.array([ [2,7],[10,5] ])
print(myarray6.min())
print(myarray6.max())
print(myarray6.sum())

2
10
24


In [13]:
# Ravel 
myarray7 = np.array([ [2,7],[10,5] ])
print(myarray7.ravel())
x = myarray7.ravel()
print(x.ndim)

[ 2  7 10  5]
1
