In [1]:
import numpy as np

In [2]:
myarray1 = np.array([1,2,3,4])

print(myarray1.shape)

(4,)


In [4]:
myarray2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(myarray2.shape)

(3, 4)


In [10]:
myarray3 = np.array(
    [
        [
            [1,2,3,4],
            [1,2,3,4]
        ]
    ,
        [
            [1,2,3,4],
            [1,2,3,4]
        ]
    ])
print(myarray3.shape)

(2, 2, 4)


In [11]:
myarray4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(myarray4.shape)

(12,)


In [14]:
remyarray4 = myarray4.reshape(3,4)
print(remyarray4.shape)
print(remyarray4)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
myarray5 = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(myarray5.shape)
remyarray5 = myarray5.reshape(-1)
print(remyarray5)

(2, 10)
[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


In [22]:
myarray6 = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(myarray6.shape)
remyarray6 = myarray6.reshape(2,5,2)
print(remyarray6)

(2, 10)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]]
